//Users

// u-get
export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";

//Coders

// c-get
export const FETCH_CODERS_REQUEST = "FETCH_CODERS_REQUEST";
export const FETCH_CODERS_SUCCESS = "FETCH_CODERS_SUCCESS";
export const FETCH_CODERS_FAIL = "FETCH_CODERS_FAIL";

// c-delete
export const DELETE_CODERS_REQUEST = "DELETE_CODERS_REQUEST";
export const DELETE_CODERS_SUCCESS = "DELETE_CODERS_SUCCESS";
export const DELETE_CODERS_FAIL = "DELETE_CODERS_FAIL";

//Students

// s-get
export const FETCH_STUDENTS_REQUEST = "FETCH_STUDENTS_REQUEST";
export const FETCH_STUDENTS_SUCCESS = "FETCH_STUDENTS_SUCCESS";
export const FETCH_STUDENTS_FAIL = "FETCH_STUDENTS_FAIL";

// s-delete
export const DELETE_STUDENT_REQUEST = "DELETE_STUDENT_REQUEST";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
export const DELETE_STUDENT_FAIL = "DELETE_STUDENT_FAIL";

// s-edit
export const EDIT_STUDENT_REQUEST = "EDIT_STUDENT_REQUEST";
export const EDIT_STUDENT_SUCCESS = "EDIT_STUDENT_SUCCESS";
export const EDIT_STUDENT_FAIL = "EDIT_STUDENT_FAIL";
